### ISSUE TITLE
Proposal to change repository structure

### ISSUE THREAD

**Issue by tirtharajghosh** [akshitagit/open-source-DSA-code#9]
There should be separate repositories for C++ and Java. So the issues can not be skipped without having solutions for both in C++ and Java (Like we have just skipped Bubble Sort for C++ ). And also other developers will have to fork only the repository of their interest without forking any extra files of other languages.

**Comment by akshitagupta15june** [comment]
right now like i have added two folders but i will  make changes.

**Comment by akshitagupta15june** [comment]
I am creating two repo's separately thankyou so much for suggestions!

**Comment by akshitagupta15june** [comment]
@tirtharajghosh can you please add your codes in respective Repository and raise a pull request.

**Comment by tirtharajghosh** [comment]
@akshitagupta15june  sure. I ll do it

**Comment by akshitagupta15june** [comment]
@tirtharajghosh thankyou so much for suggestions looking forward for more!
